### ISSUE TITLE
Aggregate initialization crashes opt

### ISSUE THREAD

**Issue by bsobol** [triSYCL/sycl#206]
### Problem description
When I try to compile such code:
```cpp
struct Line {
    float slope;
    float intercept;
};

int main() {
    sycl::queue queue{};
    {
        queue.submit([&](sycl::handler &cgh) {
            cgh.single_task([]() {
                Line l1{0, 0};
            });
        });
    }
}
```
it fails with a opt crash in sycl->HLS conversion step ("Error in sycl->HLS conversion").

It works if I _disable_ aggregate initialization by defining construstor `Line(float s, float i) : slope{s}, intercept{i} {}` or using default member initializer `float intercept = 0`.

But the interesting thing is that it also works if pass something other than zeros to aggregate:
```cpp 
Line l1{0, 1};
```
I believe this also affects `std::array`.

Any chance for fixing this issue or at least some hint on where to look?

### Setup

- OS: Ubuntu 22.04
- triSYCL/sycl: latest unified/next
- HLS flow / hw-emu mode

**Comment by Ralender** [comment]
https://github.com/triSYCL/sycl/pull/207 should fix this issue.

explanation of the bug:
LLVM loves making anything it can into a memset but memset are handled poorly by the HLS backend.
so our passes will turn memset back into stores of constants. there was a bug in generation of constant that need to be stored.
it doesn't happened for {0, 1} because it cannot be turned into a memset.

**Comment by bsobol** [comment]
This fix does the job for this issue, many thanks for help!
